<a href="https://colab.research.google.com/github/feandresilva/exercicios_Pandas/blob/main/dataset_acidentes2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import plotly.express as px
pd.set_option('display.max_columns', None)
df_acidentes = pd.read_csv("https://cognitrilha.com.br/datasets/demostrativo_acidentes_eco050.csv.gz", encoding= "iso-8859-1", sep=";", decimal = ",")
df_eco = pd.read_csv("https://cognitrilha.com.br/datasets/demostrativo_acidentes_eco101.csv.gz", encoding= "iso-8859-1", sep=";", decimal = ",")
df_ecosul = pd.read_csv("https://cognitrilha.com.br/datasets/demostrativo_acidentes_ecosul.csv.gz", encoding= "iso-8859-1", sep=";", decimal = ",")

Crie 3 DataFrames do pandas com os arquivos acima.

Crie um DataFrame com a junção dos outros 3 (use pd.concat)

Normalize os dados da coluna  "tipo_de_ocorrencia"

Normalize os dados da coluna "sentido"

Remova as linhas com valores nulos.

Crie uma coluna "vítimas_totais" com a soma de todas as contagens de vítimas para cada acidente

Mostre um gráfico de pizza com os percentuais dos estados das vítimas (ilesos, levemente feridos, moderadamente feridos, gravemente feridos e mortos) para todos os acidentes do DataFrame que possuem ao menos uma vítima.

Mostre a quantidade de acidentes totais de cada trecho, em um gráfico de barras empilhado,  onde as pilhas representam o sentido (norte vs sul).
Dica: utilize df.pivot + df.plot.bar(..., stacked=True)

Sobre o dataframe unificado, faça um gráfico de linhas que mostre a evolução de acidentes ano a ano, desde o início do período, onde cada linha representa um trecho da estrada, os valores são a média de total de vítimas por acidente, e cada linha é exibida em uma cor diferente.

In [ ]:
#Crie 3 DataFrames do pandas com os arquivos acima.
display(df_eco.head())
display(df_ecosul.head())
display(df_acidentes.head())

,data,horario,n_da_ocorrencia,tipo_de_ocorrencia,km,trecho,sentido,tipo_de_acidente,automovel,bicicleta,caminhao,moto,onibus,outros,tracao_animal,transporte_de_cargas_especiais,trator_maquinas,utilitarios,ilesos,levemente_feridos,moderadamente_feridos,gravemente_feridos,mortos
0,11/11/2013,12:18:00,3.0,Acidente c,103.0,BR-101/ES,Norte,Tombamento,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0
1,11/11/2013,02:40:00,13.0,Acidente s,368.0,BR-101/ES,Sul,Choque com Objeto Fixo,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0
2,11/11/2013,09:18:00,53.0,Acidente c,305.0,BR-101/ES,Sul,Colisão Frontal,0,0,1,1,0,0,0,0,0,0,1,0,0,0,1
3,11/11/2013,09:58:00,57.0,Acidente s,262.0,BR-101/ES,Sul,Engavetamento,2,0,1,0,0,0,0,0,0,0,1,0,0,0,0
4,11/11/2013,10:34:00,61.0,Acidente s,357.0,BR-101/ES,Sul,Capotamento,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0

,data,horario,n_da_ocorrencia,tipo_de_ocorrencia,km,trecho,sentido,tipo_de_acidente,automovel,bicicleta,caminhao,moto,onibus,outros,tracao_animal,transporte_de_cargas_especiais,trator_maquinas,utilitarios,ilesos,levemente_feridos,moderadamente_feridos,gravemente_feridos,mortos
0,02/01/2010,06:52:00,74,sem vítima,529.5,BR-116/RS,Norte,Abalr.Mesmo Sentido,0,0,2,0,0,0,0,0,0,0,2,0,0,0,0
1,03/01/2010,02:33:00,7,sem vítima,42.7,BR-392/RS,Sul,Abalr.Transversal,0,0,2,0,0,0,0,0,0,0,3,0,0,0,0
2,03/01/2010,06:02:00,13,sem vítima,35.7,BR-392/RS,Norte,Saída de Pista,1,0,2,0,0,0,0,0,0,0,1,0,0,0,0
3,03/01/2010,10:57:00,34,sem vítima,449.2,BR-116/RS,Norte,Abalr.Transversal,0,0,2,0,1,0,0,0,0,0,3,0,0,0,0
4,03/01/2010,12:14:00,48,com vítima,93.7,BR-392/RS,Norte,Tombamento,0,0,2,1,0,0,0,0,0,0,1,1,0,0,0

,data,horario,n_da_ocorrencia,tipo_de_ocorrencia,km,trecho,sentido,tipo_de_acidente,automovel,bicicleta,caminhao,moto,onibus,outros,tracao_animal,transporte_de_cargas_especiais,trator_maquinas,utilitarios,ilesos,levemente_feridos,moderadamente_feridos,gravemente_feridos,mortos
0,08/07/2014,04:27:00,97,sem vítima,60.0,BR-050/MG,Sul,Colisão Traseira,2,0,0,0,0,0,0,0,0,0,5,0,0,0,0
1,09/07/2014,01:16:00,5,com vítima,133.8,BR-050/MG,Sul,Capotamento,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0
2,09/07/2014,07:14:00,22,sem vítima,22.0,BR-050/MG,Norte,Saida de Pista,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0
3,09/07/2014,08:34:00,37,sem vítima,140.0,BR-050/MG,Norte,Queda de Moto,0,0,0,1,0,0,0,0,0,0,2,0,0,0,0
4,09/07/2014,11:21:00,56,sem vítima,120.9,BR-050/GO,Norte,Colisão Traseira,0,0,2,0,1,0,0,0,0,0,22,0,0,0,0

In [ ]:
#Crie um DataFrame com a junção dos outros 3 (use pd.concat)
df_unificado = pd.concat([df_acidentes, df_eco, df_ecosul])
df_unificado.head()

,data,horario,n_da_ocorrencia,tipo_de_ocorrencia,km,trecho,sentido,tipo_de_acidente,automovel,bicicleta,caminhao,moto,onibus,outros,tracao_animal,transporte_de_cargas_especiais,trator_maquinas,utilitarios,ilesos,levemente_feridos,moderadamente_feridos,gravemente_feridos,mortos
0,08/07/2014,04:27:00,97,sem vítima,60.0,BR-050/MG,Sul,Colisão Traseira,2,0,0,0,0,0,0,0,0,0,5,0,0,0,0
1,09/07/2014,01:16:00,5,com vítima,133.8,BR-050/MG,Sul,Capotamento,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0
2,09/07/2014,07:14:00,22,sem vítima,22.0,BR-050/MG,Norte,Saida de Pista,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0
3,09/07/2014,08:34:00,37,sem vítima,140.0,BR-050/MG,Norte,Queda de Moto,0,0,0,1,0,0,0,0,0,0,2,0,0,0,0
4,09/07/2014,11:21:00,56,sem vítima,120.9,BR-050/GO,Norte,Colisão Traseira,0,0,2,0,1,0,0,0,0,0,22,0,0,0,0

In [ ]:
#Normalize os dados da coluna "tipo_de_ocorrencia"
display(df_unificado["tipo_de_ocorrencia"].unique())
df_unificado["tipo_de_ocorrencia_norm"] = df_unificado["tipo_de_ocorrencia"]
df_unificado["tipo_de_ocorrencia_norm"] = df_unificado["tipo_de_ocorrencia_norm"].replace({"sem vítima": "Sem vitima", "Sem vítima": "Sem vitima", "Acidente s": "Sem vitima", "com vítima": "Com vitima", "Com vítima": "Com vitima", "Acidente c": "Com vitima", "Atropelame": "Com vitima"})
display(df_unificado["tipo_de_ocorrencia_norm"].unique())

array(['sem vítima', 'com vítima', 'ac03 - Aci', 'ac02 - Aci',
       'ac01 - Aci', 'ac04 - Aci', 'Sem vítima', 'Com vítima',
       'Acidente c', 'Acidente s', 'Atropelame'], dtype=object)

array(['Sem vitima', 'Com vitima', 'ac03 - Aci', 'ac02 - Aci',
       'ac01 - Aci', 'ac04 - Aci'], dtype=object)

In [ ]:
#Normalize os dados da coluna "sentido"
df_unificado["sentido"] = df_unificado["sentido"].replace({"Crescente": "Sul", "Decrescente": "Norte"})
df_unificado["sentido"].unique()

array(['Sul', 'Norte', 'Leste', 'Oeste', nan], dtype=object)

In [ ]:
#Remova as linhas com valores nulos.
df_unificado = df_unificado.dropna()
df_unificado["sentido"].unique()

array(['Sul', 'Norte', 'Leste', 'Oeste'], dtype=object)

In [ ]:
#Crie uma coluna "vítimas_totais" com a soma de todas as contagens de vítimas para cada acidente
df_unificado["vitimas_totais"] = df_unificado["levemente_feridos"] + df_unificado["moderadamente_feridos"] + df_unificado["gravemente_feridos"]
df_unificado.head()

,data,horario,n_da_ocorrencia,tipo_de_ocorrencia,km,trecho,sentido,tipo_de_acidente,automovel,bicicleta,caminhao,moto,onibus,outros,tracao_animal,transporte_de_cargas_especiais,trator_maquinas,utilitarios,ilesos,levemente_feridos,moderadamente_feridos,gravemente_feridos,mortos,tipo_de_ocorrencia_norm,vitimas_totais
0,08/07/2014,04:27:00,97,sem vítima,60.0,BR-050/MG,Sul,Colisão Traseira,2,0,0,0,0,0,0,0,0,0,5,0,0,0,0,Sem vitima,0
1,09/07/2014,01:16:00,5,com vítima,133.8,BR-050/MG,Sul,Capotamento,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,Com vitima,1
2,09/07/2014,07:14:00,22,sem vítima,22.0,BR-050/MG,Norte,Saida de Pista,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,Sem vitima,0
3,09/07/2014,08:34:00,37,sem vítima,140.0,BR-050/MG,Norte,Queda de Moto,0,0,0,1,0,0,0,0,0,0,2,0,0,0,0,Sem vitima,0
4,09/07/2014,11:21:00,56,sem vítima,120.9,BR-050/GO,Norte,Colisão Traseira,0,0,2,0,1,0,0,0,0,0,22,0,0,0,0,Sem vitima,0

In [ ]:
#Mostre um gráfico de pizza com os percentuais dos estados das vítimas (ilesos, levemente feridos, moderadamente feridos, gravemente feridos e mortos)
#para todos os acidentes do DataFrame que possuem ao menos uma vítima
df_unificado_filtrado = df_unificado[df_unificado["tipo_de_ocorrencia_norm"] == "Com vitima"]
df_grafico_pizza = (df_unificado_filtrado[["ilesos", "levemente_feridos", "moderadamente_feridos", "gravemente_feridos", "mortos"]].sum() / df_unificado_filtrado[["ilesos", "levemente_feridos", "moderadamente_feridos", "gravemente_feridos", "mortos"]].sum().sum()*100)
df_grafico_pizza = df_grafico_pizza.reset_index()
df_grafico_pizza["index"] = df_grafico_pizza["index"].replace({"ilesos": "Ilesos", "levemente_feridos": "Levemente feridos", "moderadamente_feridos": "Moderadamente feridos", "gravemente_feridos": "Gravemente feridos", "mortos": "Mortos"})
df_grafico_pizza

                   index          0
0                 Ilesos  43.753092
1      Levemente feridos  27.687077
2  Moderadamente feridos  21.000622
3     Gravemente feridos   4.448757
4                 Mortos   3.110451

In [ ]:
fig = px.pie(df_grafico_pizza, values= 0, names="index")
fig.show()

In [ ]:
#Mostre a quantidade de acidentes totais de cada trecho, em um gráfico de barras empilhado,
#onde as pilhas representam o sentido (norte vs sul).
#Dica: utilize df.pivot + df.plot.bar(..., stacked=True)

df_barras_empilhadas = df_unificado.groupby("trecho")["sentido"].value_counts()
df_barras_empilhadas = df_barras_empilhadas.reset_index()
fig = px.bar(df_barras_empilhadas, x="trecho", y="count", color="sentido", barmode= "stack")
fig.show()

In [ ]:
#Sobre o dataframe unificado, faça um gráfico de linhas que mostre a evolução de acidentes ano a ano,
#desde o início do período, onde cada linha representa um trecho da estrada,
#os valores são a média de total de vítimas por acidente, e cada linha é exibida em uma cor diferente.
df_unificado = df_unificado.dropna(subset = "data")
df_unificado["ano"] = pd.to_datetime(df_unificado["data"], format= "%d/%m/%Y").dt.year
df_grafico_linhas = df_unificado[(df_unificado["ano"]>= 2015) & (df_unificado["ano"]<= 2024)]
df_grafico_linhas = df_grafico_linhas.groupby(["trecho", "ano"])["vitimas_totais"].mean().reset_index()
fig = px.line(df_grafico_linhas, x="ano", y= "vitimas_totais", color= "trecho")
fig.show()