<a href="https://colab.research.google.com/github/feandresilva/exercicios_Pandas/blob/main/dataset_imoveis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import plotly.express as px
pd.set_option('display.max_columns', None)

df_imoveis = pd.read_csv("https://cognitrilha.com.br/datasets/imoveis_aquisicoes_brasil.csv.gz")
df_imoveis

,logradouro,tipo_logradouro,bairro,cidade,cep,tipo,valor,data_aquisicao
0,Quinta do Sol,Rua,Alto da Pedreira,Belo Horizonte,30840439,Terreno,1192500.0,2015-10-10
1,Antonio Loureiro,Rua,Alto da Pedreira,Belo Horizonte,30026486,Casa,1127500.0,2016-12-02
2,Canario Branco Central,Rua,Alto da Pedreira,Belo Horizonte,31093672,Kitnet,247000.0,2017-05-11
3,das Palmeiras,Avenida,Alto da Pedreira,Belo Horizonte,30166283,Cobertura,2095000.0,2017-05-17
4,Antonio Loureiro,Rua,Alto da Pedreira,Belo Horizonte,30031522,Terreno,1392500.0,2019-04-06
...,...,...,...,...,...,...,...,...
1495,Veredas do Lago,Rua,Vila Primavera,Sao Paulo,4607074,Casa,1132500.0,2024-06-22
1496,dos Ipes,Estrada,Vila Primavera,Sao Paulo,5744464,Casa,1700000.0,2024-12-14
1497,Benedito Campos,Rua,Vila Primavera,Sao Paulo,5563640,Casa,757500.0,2025-04-19
1498,Joao Marin,Rua,Vila Primavera,Sao Paulo,5177091,Sobrado,2205000.0,2025-07-04
1499,Monte Claro,Travessa,Vila Primavera,Sao Paulo,5614926,Kitnet,279000.0,2025-10-22

In [ ]:
#Quantas colunas o dataset possui?
df_imoveis

,logradouro,tipo_logradouro,bairro,cidade,cep,tipo,valor,data_aquisicao
0,Quinta do Sol,Rua,Alto da Pedreira,Belo Horizonte,30840439,Terreno,1192500.0,2015-10-10
1,Antonio Loureiro,Rua,Alto da Pedreira,Belo Horizonte,30026486,Casa,1127500.0,2016-12-02
2,Canario Branco Central,Rua,Alto da Pedreira,Belo Horizonte,31093672,Kitnet,247000.0,2017-05-11
3,das Palmeiras,Avenida,Alto da Pedreira,Belo Horizonte,30166283,Cobertura,2095000.0,2017-05-17
4,Antonio Loureiro,Rua,Alto da Pedreira,Belo Horizonte,30031522,Terreno,1392500.0,2019-04-06
...,...,...,...,...,...,...,...,...
1495,Veredas do Lago,Rua,Vila Primavera,Sao Paulo,4607074,Casa,1132500.0,2024-06-22
1496,dos Ipes,Estrada,Vila Primavera,Sao Paulo,5744464,Casa,1700000.0,2024-12-14
1497,Benedito Campos,Rua,Vila Primavera,Sao Paulo,5563640,Casa,757500.0,2025-04-19
1498,Joao Marin,Rua,Vila Primavera,Sao Paulo,5177091,Sobrado,2205000.0,2025-07-04
1499,Monte Claro,Travessa,Vila Primavera,Sao Paulo,5614926,Kitnet,279000.0,2025-10-22

In [ ]:
#Quantas colunas numéricas o dataset possui?
df_imoveis.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   logradouro       1500 non-null   object
 1   tipo_logradouro  1500 non-null   object
 2   bairro           1500 non-null   object
 3   cidade           1500 non-null   object
 4   cep              1500 non-null   int64
 5   tipo             1500 non-null   object
 6   valor            1500 non-null   float64
 7   data_aquisicao   1500 non-null   object
dtypes: float64(1), int64(1), object(6)
memory usage: 93.9+ KB

In [ ]:
#Quantas linhas tem o dataset?
df_imoveis

,logradouro,tipo_logradouro,bairro,cidade,cep,tipo,valor,data_aquisicao
0,Quinta do Sol,Rua,Alto da Pedreira,Belo Horizonte,30840439,Terreno,1192500.0,2015-10-10
1,Antonio Loureiro,Rua,Alto da Pedreira,Belo Horizonte,30026486,Casa,1127500.0,2016-12-02
2,Canario Branco Central,Rua,Alto da Pedreira,Belo Horizonte,31093672,Kitnet,247000.0,2017-05-11
3,das Palmeiras,Avenida,Alto da Pedreira,Belo Horizonte,30166283,Cobertura,2095000.0,2017-05-17
4,Antonio Loureiro,Rua,Alto da Pedreira,Belo Horizonte,30031522,Terreno,1392500.0,2019-04-06
...,...,...,...,...,...,...,...,...
1495,Veredas do Lago,Rua,Vila Primavera,Sao Paulo,4607074,Casa,1132500.0,2024-06-22
1496,dos Ipes,Estrada,Vila Primavera,Sao Paulo,5744464,Casa,1700000.0,2024-12-14
1497,Benedito Campos,Rua,Vila Primavera,Sao Paulo,5563640,Casa,757500.0,2025-04-19
1498,Joao Marin,Rua,Vila Primavera,Sao Paulo,5177091,Sobrado,2205000.0,2025-07-04
1499,Monte Claro,Travessa,Vila Primavera,Sao Paulo,5614926,Kitnet,279000.0,2025-10-22

In [ ]:
#Escreva o endereço completo do imóvel com o maior valor
df_imoveis["valor"].max()
df_imoveis[df_imoveis["valor"]== 6570000.0]

,logradouro,tipo_logradouro,bairro,cidade,cep,tipo,valor,data_aquisicao
328,Joao Marin,Avenida,Parque Barigui Novo,Curitiba,82034457,Galpao,6570000.0,2019-10-17

In [ ]:
#Escreva o endereço completo do imóvel com o menor valor
df_imoveis["valor"].min()
df_imoveis[df_imoveis["valor"]== 87000.0]

,logradouro,tipo_logradouro,bairro,cidade,cep,tipo,valor,data_aquisicao
523,das Cerejeiras,Rua,Vila Lagoa Serena,Fortaleza,60289143,Kitnet,87000.0,2021-01-10
903,Joao Marin,Estrada,Parque das Aroeiras,Ribeirao Preto,14107955,Kitnet,87000.0,2024-06-11

In [ ]:
#Escreva o endereço completo do imóvel adquirido mais recentemente (maior data de aquisição)
df_imoveis["data_aquisicao"].max()
df_imoveis[df_imoveis["data_aquisicao"] == "2026-04-25"]

,logradouro,tipo_logradouro,bairro,cidade,cep,tipo,valor,data_aquisicao
610,Paineiras,Avenida,Jardim Icarai Novo,Niteroi,24342897,Apartamento,1237500.0,2026-04-25

a) Liste 4 funções do pandas que podemos utilizar para ler dados, além da read_csv.
pd.read_json()
pd.read_html()
pd.read_sql()
pd.read_sql_table()

b) Liste 6 funções de agregação que podemos utilizar em um groupby.
sum()
mean()
median()
min()
max()
count()


c) Liste 8 tipos de gráfico que podemos exibir com o DataFrame.plot?
line
bar
barh
pie
hist
box
scatter
density