<a href="https://colab.research.google.com/github/feandresilva/exercicios_Pandas/blob/main/dataset_brasileirao_2025.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import plotly.express as px
pd.set_option('display.max_columns', None)

df_brasileirao = pd.read_excel("https://github.com/schneider8357/projeto_brasileirao/raw/refs/heads/main/dados_brasileirao_serie_a_2025.xlsx")
df_brasileirao

     rodada           nome_time1  gols_time1  gols_time2           nome_time2
0         1             Flamengo           1           1        Internacional
1         1        Vasco da Gama           2           1               Santos
2         1            Palmeiras           0           0             Botafogo
3         1            São Paulo           0           0                Sport
4         1  Red Bull Bragantino           2           2                Ceará
..      ...                  ...         ...         ...                  ...
375      38             Atlético           5           0        Vasco da Gama
376      38        Internacional           3           1  Red Bull Bragantino
377      38              Vitória           1           0            São Paulo
378      38                Ceará           1           3            Palmeiras
379      38                Sport           0           4               Grêmio

[380 rows x 5 columns]

Qual time teve o maior número de gols?

Qual time teve o maior saldo de gols?

Qual time teve o maior número de vitórias?

Monte a tabela final do campeonato conforme a seguinte regra:

-Primeiro ordenado pelo maior número de pontos (3 pontos cada vitória, 1 ponto cada empate)

-Depois ordenado pelo Maior saldo de gols

-E por último, ordenado pelo maior número de gols pró

Faça um programa que receba como entrada o nome de um time e mostre em gráficos a evolução de um time pelo campeonato.
Exiba em gráficos de linha:
- Evolução de gols feitos
- Evolução de gols tomados
- Evolução de saldo de gols

Mostre em um gráfico de pizza:
- Percentual de vitórias vs empates vs derrotas

Informe também a posição final do time no campeonato.

Ordene pelo número da rodada.

In [ ]:
#Qual time teve o maior número de gols?
df_gols_time1 = df_brasileirao[["nome_time1", "gols_time1"]]
df_gols_time2 = df_brasileirao[["nome_time2", "gols_time2"]]
df_gols_time1 = df_gols_time1.rename(columns={"nome_time1": "nome_time", "gols_time1": "gols_time"})
df_gols_time2 = df_gols_time2.rename(columns={"nome_time2": "nome_time", "gols_time2": "gols_time"})
df_brasileirao_unificado = pd.concat([df_gols_time1, df_gols_time2])
df_brasileiro_unificado = df_brasileirao_unificado.groupby("nome_time")["gols_time"].sum().reset_index()
df_brasileiro_unificado = df_brasileiro_unificado.rename(columns={"gols_time": "gols_pro"})
df_brasileiro_unificado

              nome_time  gols_pro
0              Atlético        43
1                 Bahia        50
2              Botafogo        58
3                 Ceará        34
4           Corinthians        42
5              Cruzeiro        55
6              Flamengo        78
7            Fluminense        50
8             Fortaleza        43
9                Grêmio        47
10        Internacional        44
11            Juventude        35
12             Mirassol        63
13            Palmeiras        66
14  Red Bull Bragantino        45
15               Santos        45
16                Sport        28
17            São Paulo        43
18        Vasco da Gama        55
19              Vitória        35

In [ ]:
#Qual time teve o maior saldo de gols?
df_saldo_time1 = df_brasileirao[["nome_time1", "gols_time1", "gols_time2"]]
df_saldo_time1["saldo"] = df_saldo_time1["gols_time1"] - df_saldo_time1["gols_time2"]
df_saldo_time1 = df_saldo_time1.rename(columns={"nome_time1": "nome_time"})
df_saldo_filtrado1 = df_saldo_time1[["nome_time", "saldo"]]
df_saldo_time2 = df_brasileirao[["nome_time2", "gols_time2", "gols_time1"]]
df_saldo_time2["saldo"] = df_saldo_time2["gols_time2"] - df_saldo_time2["gols_time1"]
df_saldo_time2 = df_saldo_time2.rename(columns={"nome_time2": "nome_time"})
df_saldo_filtrado2 = df_saldo_time2[["nome_time", "saldo"]]
df_saldo_unificado = pd.concat([df_saldo_filtrado1, df_saldo_filtrado2])
df_saldo_unificado = df_saldo_unificado.groupby("nome_time")["saldo"].sum().reset_index()
df_saldo_unificado

/tmp/ipykernel_12395/4034437707.py:3: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/tmp/ipykernel_12395/4034437707.py:7: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

              nome_time  saldo
0              Atlético     -1
1                 Bahia      4
2              Botafogo     20
3                 Ceará     -6
4           Corinthians     -5
5              Cruzeiro     24
6              Flamengo     51
7            Fluminense     11
8             Fortaleza    -15
9                Grêmio     -3
10        Internacional    -13
11            Juventude    -34
12             Mirassol     24
13            Palmeiras     33
14  Red Bull Bragantino    -12
15               Santos     -5
16                Sport    -47
17            São Paulo     -4
18        Vasco da Gama     -5
19              Vitória    -17

In [ ]:
#Qual time teve o maior número de vitórias?
df_time1 = df_brasileirao[["nome_time1", "gols_time1", "gols_time2"]]
df_vitoria1 = df_time1[df_time1["gols_time1"] > df_time1["gols_time2"]]
df_vitoria1 = df_vitoria1.rename(columns={"nome_time1": "nome_time"})
df_vitoria1_fitlrado = df_vitoria1["nome_time"]
df_time2 = df_brasileirao[["nome_time1", "gols_time1", "gols_time2", "nome_time2"]]
df_vitoria2 = df_time2[df_time2["gols_time2"] > df_time2["gols_time1"]]
df_vitoria2 = df_vitoria2.rename(columns={"nome_time2": "nome_time"})
df_vitoria2_filtrado = df_vitoria2["nome_time"]
df_vitoria_unificado = pd.concat([df_vitoria1_fitlrado, df_vitoria2_filtrado])
df_vitoria_unificado = df_vitoria_unificado.value_counts().reset_index()
df_vitoria_unificado = df_vitoria_unificado.rename(columns={"count": "vitorias"})
df_vitoria_unificado

              nome_time  vitorias
0              Flamengo        23
1             Palmeiras        23
2              Cruzeiro        19
3            Fluminense        19
4              Mirassol        18
5              Botafogo        17
6                 Bahia        17
7             São Paulo        14
8   Red Bull Bragantino        14
9         Vasco da Gama        13
10               Grêmio        13
11             Atlético        12
12          Corinthians        12
13               Santos        12
14            Fortaleza        11
15                Ceará        11
16              Vitória        11
17        Internacional        11
18            Juventude         9
19                Sport         2

In [ ]:
#Quantificando os empates
df_empate1 = df_brasileirao[["nome_time1", "gols_time1", "gols_time2"]]
df_empate1_filtrado = df_empate1[df_empate1["gols_time1"] == df_empate1["gols_time2"]]
df_empate1_filtrado = df_empate1_filtrado.rename(columns={"nome_time1": "nome_time"})
df_empate1_final = df_empate1_filtrado["nome_time"]
df_empate2 = df_brasileirao[["gols_time1", "gols_time2", "nome_time2"]]
df_empate2_filtrado = df_empate2[df_empate2["gols_time1"] == df_empate2["gols_time2"]]
df_empate2_filtrado = df_empate2_filtrado.rename(columns={"nome_time2": "nome_time"})
df_empate2_final = df_empate2_filtrado["nome_time"]
df_empate_unificado = pd.concat([df_empate1_final, df_empate2_final])
df_empate_unificado = df_empate_unificado.value_counts().reset_index()
df_empate_unificado = df_empate_unificado.rename(columns={"count": "empates"})
df_empate_unificado

              nome_time  empates
0              Cruzeiro       13
1              Mirassol       13
2              Atlético       12
3              Botafogo       12
4               Vitória       12
5                 Sport       11
6         Internacional       11
7                Santos       11
8           Corinthians       11
9                Grêmio       10
10                Ceará       10
11             Flamengo       10
12            Fortaleza       10
13                Bahia        9
14            São Paulo        9
15            Juventude        8
16           Fluminense        7
17            Palmeiras        7
18  Red Bull Bragantino        6
19        Vasco da Gama        6

In [ ]:
#Monte a tabela final do campeonato conforme a seguinte regra:
#Primeiro ordenado pelo maior número de pontos (3 pontos cada vitória, 1 ponto cada empate)
#Depois ordenado pelo Maior saldo de gols
#E por último, ordenado pelo maior número de gols pró
df_unificado_saldo_vitorias = df_saldo_unificado.set_index("nome_time").join(df_vitoria_unificado.set_index("nome_time"), how="left")
df_unificado_saldo_vitorias = df_unificado_saldo_vitorias.reset_index()
df_tabela_final_intermediaria = df_brasileiro_unificado.set_index("nome_time").join(df_unificado_saldo_vitorias.set_index("nome_time"), how= "left")
df_tabela_final_intermediaria = df_tabela_final_intermediaria.reset_index()
df_tabela_completa = df_empate_unificado.set_index("nome_time").join(df_tabela_final_intermediaria.set_index("nome_time"), how="left")
df_tabela_completa["pontos"] = (df_tabela_completa["vitorias"] * 3) + df_tabela_completa["empates"]
df_tabela_completa["derrotas"] = 38 - (df_tabela_completa["vitorias"] + df_tabela_completa["empates"])
df_tabela_completa["gols_tomados"] = df_tabela_completa["gols_pro"] - df_tabela_completa["saldo"]
df_tabela_completa.sort_values(["pontos", "saldo", "gols_pro"], ascending = False)[["pontos", "vitorias", "empates", "derrotas", "gols_pro", "gols_tomados", "saldo"]]

,pontos,vitorias,empates,derrotas,gols_pro,gols_tomados,saldo
nome_time,,,,,,,
Flamengo,79,23,10,5,78,27,51
Palmeiras,76,23,7,8,66,33,33
Cruzeiro,70,19,13,6,55,31,24
Mirassol,67,18,13,7,63,39,24
Fluminense,64,19,7,12,50,39,11
Botafogo,63,17,12,9,58,38,20
Bahia,60,17,9,12,50,46,4
São Paulo,51,14,9,15,43,47,-4
Grêmio,49,13,10,15,47,50,-3
Atlético,48,12,12,14,43,44,-1
Red Bull Bragantino,48,14,6,18,45,57,-12
Santos,47,12,11,15,45,50,-5
Corinthians,47,12,11,15,42,47,-5
Vasco da Gama,45,13,6,19,55,60,-5
Vitória,45,11,12,15,35,52,-17
Internacional,44,11,11,16,44,57,-13
Ceará,43,11,10,17,34,40,-6
Fortaleza,43,11,10,17,43,58,-15
Juventude,35,9,8,21,35,69,-34
Sport,17,2,11,25,28,75,-47

In [ ]:
#Faça um programa que receba como entrada o nome de um time e mostre em gráficos a evolução de um time pelo campeonato.
#Exiba em gráficos de linha:
#Evolução de gols feitos
#Evolução de gols tomados
#Evolução de saldo de gols

time_escolhido = input("Escolha um time: ")

df_rodadas1 = df_brasileirao[["rodada", "nome_time1", "gols_time1", "gols_time2", "nome_time2"]]
df_rodadas1["saldo"] = df_rodadas1["gols_time1"] - df_rodadas1["gols_time2"]
df_rodadas1 = df_rodadas1.rename(columns={"nome_time1": "nome_time", "gols_time1": "gols_pro"})
df_rodadas1_filtrado = df_rodadas1[["rodada", "nome_time", "gols_pro", "saldo"]]

df_rodadas2 = df_brasileirao[["rodada", "nome_time1", "gols_time1", "gols_time2", "nome_time2"]]
df_rodadas2["saldo"] = df_rodadas2["gols_time2"] - df_rodadas2["gols_time1"]
df_rodadas2 = df_rodadas2.rename(columns={"nome_time2": "nome_time", "gols_time2": "gols_pro"})
df_rodadas2_filtrado = df_rodadas2[["rodada", "nome_time", "gols_pro", "saldo"]]

df_rodadas_final = pd.concat([df_rodadas2_filtrado, df_rodadas1_filtrado])
df_rodadas_final["gols_tomados"] = df_rodadas_final["gols_pro"] - df_rodadas_final["saldo"]


df_evolucao_gols_feitos = df_rodadas_final.groupby(["rodada", "nome_time"])["gols_pro"].sum()
df_evolucao_gols_feitos = df_evolucao_gols_feitos.reset_index()
df_escolha_usuario_gols_feitos = df_evolucao_gols_feitos[df_evolucao_gols_feitos["nome_time"]== time_escolhido]
fig = px.line(df_escolha_usuario_gols_feitos, x="rodada", y="gols_pro", color="nome_time")
display(fig.show())

df_evolucao_gols_tomados = df_rodadas_final.groupby(["rodada", "nome_time"])["gols_tomados"].sum()
df_evolucao_gols_tomados = df_evolucao_gols_tomados.reset_index()
df_escolha_usuario_gols_tomados = df_evolucao_gols_tomados[df_evolucao_gols_tomados["nome_time"]== time_escolhido]
fig = px.line(df_escolha_usuario_gols_tomados, x="rodada", y="gols_tomados", color="nome_time")
display(fig.show())

df_evolucao_saldo = df_rodadas_final.groupby(["rodada", "nome_time"])["saldo"].sum()
df_evolucao_saldo = df_evolucao_saldo.reset_index()
df_escolha_usuario_saldo = df_evolucao_saldo[df_evolucao_saldo["nome_time"] == time_escolhido]
fig = px.line(df_escolha_usuario_saldo, x="rodada", y="saldo", color="nome_time")
display(fig.show())

df_tabela_completa = df_tabela_completa.reset_index()
df_grafico_pizza = df_tabela_completa[["nome_time", "vitorias", "empates", "derrotas"]]
df_escolha_usuario = df_grafico_pizza[df_grafico_pizza["nome_time"]== time_escolhido]
df_escolha_usuario_percentual = df_escolha_usuario[["vitorias", "empates", "derrotas"]] / 38 *100
df_escolha_usuario_percentual = df_escolha_usuario_percentual.reset_index(drop=True)
df_escolha_usuario_percentual = df_escolha_usuario_percentual.T
df_escolha_usuario_percentual = df_escolha_usuario_percentual.reset_index()
df_escolha_usuario_percentual = df_escolha_usuario_percentual.rename(columns={"index":"Resultado", 0: "Porcentagem"})
fig = px.pie(df_escolha_usuario_percentual, values="Porcentagem", names="Resultado")
display(fig.show())

df_tabela_final_ordenada = df_tabela_completa.sort_values(["pontos", "saldo", "gols_pro"], ascending = False)[["nome_time", "pontos", "vitorias", "empates", "derrotas", "gols_pro", "gols_tomados", "saldo"]]
df_tabela_final_ordenada = df_tabela_final_ordenada.reset_index(drop=True)
df_tabela_final_ordenada["posicao"] = df_tabela_final_ordenada.index + 1
df_escolha_usuario_posicao_final = df_tabela_final_ordenada[df_tabela_final_ordenada["nome_time"]== time_escolhido]
df_escolha_usuario_posicao_final[["nome_time", "posicao"]]

Escolha um time: Corinthians

None

None

None

None

      nome_time  posicao
12  Corinthians       13