<a href="https://colab.research.google.com/github/feandresilva/exercicios_Pandas/blob/main/ODS_dataframe.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
df_ODS = pd.read_csv("https://github.com/marcelovc785/AP2_PML_8001/raw/main/IDSC_BR_AP2_E01d2G01.csv", encoding="iso-8859-1", sep= ";", decimal = ",")
df_ODS.head()

,id,Territorialidade,População_Ref,Pontuação Indice ODS 2022,Classificação 2022,2022 ODS 1,2022 ODS 3,2022 ODS 5,Pontuação Indice ODS 2019,Classificação 2019,2019 ODS 1,2019 ODS 3,2019 ODS 5
0,5200050.0,;Abadia de Goiás;GO;CO;,19128.0,48.06,2226.0,42.39,64.57,33.67,48.63,2109.0,44.36,39.52,33.67
1,3100104.0,;Abadia dos Dourados;MG;SE;,6272.0,45.65,3143.0,51.21,65.08,16.16,46.84,2688.0,53.63,69.53,16.16
2,5200100.0,;Abadiânia;GO;CO;,17228.0,49.36,1773.0,44.83,76.23,27.80,50.11,1648.0,43.71,60.24,27.80
3,3100203.0,;Abaeté;MG;SE;,22675.0,52.73,899.0,47.13,77.96,15.08,49.59,1801.0,47.60,57.21,15.08
4,1500107.0,;Abaetetuba;PA;N;,158188.0,37.92,5293.0,38.08,71.62,20.20,38.11,5215.0,37.64,56.52,20.20

Qual o estado da região Sudeste que teve o menor valor na média da “ODS 3 do

*   Item da lista
*   Item da lista


Ano 2022”, organizada por “UF”?


Qual a cidade do estado que reponde corretamente o item anterior, e que teve o valor da “ODS ano 2022” mais próximo da média do estado inteiro?


Qual foi a cidade do estado do Rio de Janeiro que teve o menor crescimento da “ODS 5” entre os anos 2019 e 2022


Aproximadamente, qual a média da "ODS 5" entre os anos 2019 e 2022 da região
Nordeste?


Qual foi o estado da região Nordeste que teve a maior média da coluna ODS 5 do ano 2022, organizada por “UF”?


Qual foi a cidade do estado que responde corretamente o item anterior que teve o
maior crescimento da Coluna ODS 5 entre os anos 2019 e 2022?

In [ ]:
#Qual o estado da região Sudeste que teve o menor valor na média da “ODS 3 do Ano 2022”, organizada por “UF”?
df_sem_nulos = df_ODS.dropna(subset=["Territorialidade"])
df_sem_nulos["UF"] = df_sem_nulos["Territorialidade"].str.split(";").str[2]
df_sem_nulos["Regiao"] = df_sem_nulos["Territorialidade"].str.split(";").str[3]
df_sudeste = df_sem_nulos[df_sem_nulos["Regiao"] == "SE"]
media_estados_sudeste = df_sudeste.groupby("UF")["2022 ODS 3"].mean().sort_values()
media_estados_sudeste

/tmp/ipykernel_627/3100454592.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_sem_nulos["UF"] = df_sem_nulos["Territorialidade"].str.split(";").str[2]
/tmp/ipykernel_627/3100454592.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_sem_nulos["Regiao"] = df_sem_nulos["Territorialidade"].str.split(";").str[3]

UF
ES    68.133846
RJ    69.518152
MG    72.152110
SP    72.278031
Name: 2022 ODS 3, dtype: float64

In [ ]:
#Qual a cidade do estado que reponde corretamente o item anterior,
#e que teve o valor da “ODS ano 2022” mais próximo da média do estado inteiro?
df_sudeste_ES = df_sudeste[df_sudeste["UF"] == "ES"]
df_sudeste_ES["Diferenca"] = (68.133846 - df_sudeste_ES["2022 ODS 3"]).abs()
df_cidade_ES = df_sudeste_ES.sort_values(by="Diferenca").head(1)
df_cidade_ES

/tmp/ipykernel_627/2627618907.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_sudeste_ES["Diferenca"] = (68.133846 - df_sudeste_ES["2022 ODS 3"]).abs()

,id,Territorialidade,População_Ref,Pontuação Indice ODS 2022,Classificação 2022,2022 ODS 1,2022 ODS 3,2022 ODS 5,Pontuação Indice ODS 2019,Classificação 2019,2019 ODS 1,2019 ODS 3,2019 ODS 5,UF,Regiao,Diferenca
5012,3205002.0,;Serra;ES;SE;,520649.0,48.19,2184.0,50.28,68.31,30.08,50.32,1603.0,49.4,56.05,30.08,ES,SE,0.176154

In [ ]:
#Qual foi a cidade do estado do Rio de Janeiro que teve o menor crescimento da “ODS 5” entre os anos 2019 e 2022
df_rio = df_sudeste[df_sudeste["UF"] == "RJ"]
df_rio["Crescimento"] = df_rio["2022 ODS 5"] - df_rio["2019 ODS 5"]
df_rio.sort_values(by= "Crescimento")

/tmp/ipykernel_627/343473588.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_rio["Crescimento"] = df_rio["2022 ODS 5"] - df_rio["2019 ODS 5"]

,id,Territorialidade,População_Ref,Pontuação Indice ODS 2022,Classificação 2022,2022 ODS 1,2022 ODS 3,2022 ODS 5,Pontuação Indice ODS 2019,Classificação 2019,2019 ODS 1,2019 ODS 3,2019 ODS 5,UF,Regiao,Crescimento
3653,3303856.0,;Paty do Alferes;RJ;SE;,29619.0,44.83,3459.0,42.99,71.07,35.10,46.83,2693.0,44.16,60.18,35.11,RJ,SE,-0.01
2718,3302304.0,;Laje do Muriaé;RJ;SE;,7336.0,46.42,2839.0,40.70,77.01,27.48,47.23,2573.0,38.53,60.02,27.49,RJ,SE,-0.01
242,3300100.0,;Angra dos Reis;RJ;SE;,167418.0,48.53,2069.0,34.80,76.65,47.12,48.31,2221.0,31.69,60.85,47.12,RJ,SE,0.00
275,3300159.0,;Aperibé;RJ;SE;,11034.0,52.29,983.0,53.81,79.61,34.31,52.17,1180.0,54.87,59.55,34.31,RJ,SE,0.00
384,3300233.0,;Armação dos Búzios;RJ;SE;,40006.0,53.07,819.0,50.47,50.05,34.60,54.91,688.0,48.43,37.98,34.60,RJ,SE,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5293,3306008.0,;Três Rios;RJ;SE;,78346.0,50.83,1361.0,43.34,72.85,53.10,52.80,1062.0,47.92,47.34,53.10,RJ,SE,0.00
5422,3306107.0,;Valença;RJ;SE;,67753.0,51.07,1279.0,42.16,51.61,28.17,48.04,2307.0,41.34,50.34,28.17,RJ,SE,0.00
5444,3306156.0,;Varre-Sai;RJ;SE;,10207.0,47.44,2451.0,35.01,74.33,33.94,47.98,2324.0,37.98,65.68,33.94,RJ,SE,0.00
5458,3306206.0,;Vassouras;RJ;SE;,33976.0,50.74,1393.0,42.78,73.32,35.61,49.71,1769.0,39.65,53.23,35.61,RJ,SE,0.00
5544,3306305.0,;Volta Redonda;RJ;SE;,261584.0,47.88,2286.0,44.90,70.29,27.56,52.43,1124.0,43.92,54.83,27.56,RJ,SE,0.00

In [ ]:
#Aproximadamente, qual a média da "ODS 5" entre os anos 2019 e 2022 da região Nordeste?
df_nordeste = df_sem_nulos[df_sem_nulos["Regiao"] == "NE"]
df_nordeste["Media ODS 5 2019"] = df_nordeste["2019 ODS 5"].mean()
df_nordeste["Media ODS 5 2022"] = df_nordeste["2022 ODS 5"].mean()
df_nordeste_media_final = (df_nordeste["Media ODS 5 2022"] + df_nordeste["Media ODS 5 2019"]) / 2
df_nordeste_media_final.head(1)

/tmp/ipykernel_627/3095460803.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_nordeste["Media ODS 5 2019"] = df_nordeste["2019 ODS 5"].mean()
/tmp/ipykernel_627/3095460803.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_nordeste["Media ODS 5 2022"] = df_nordeste["2022 ODS 5"].mean()

5    18.202651
dtype: float64

In [ ]:
#Qual foi o estado da região Nordeste que teve a maior média da coluna ODS 5 do ano 2022, organizada por “UF”?
media_estados_nordeste = df_nordeste.groupby("UF")["2022 ODS 5"].mean().sort_values(ascending=False)
media_estados_nordeste

UF
CE    25.842826
BA    23.937434
MA    20.652581
PI    18.951473
SE    17.942133
PE    13.847189
AL    12.546471
RN    12.543653
PB     8.563274
Name: 2022 ODS 5, dtype: float64

In [ ]:
#Qual foi a cidade do estado que responde corretamente o item anterior
#que teve o maior crescimento da Coluna ODS 5 entre os anos 2019 e 2022?
df_CE = df_nordeste[df_nordeste["UF"]== "CE"]
df_CE["Crescimento"] = df_CE["2022 ODS 5"] - df_CE["2019 ODS 5"]
df_CE.sort_values(by="Crescimento", ascending=False)

/tmp/ipykernel_627/1522974606.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_CE["Crescimento"] = df_CE["2022 ODS 5"] - df_CE["2019 ODS 5"]

Empty DataFrame
Columns: [2019 ODS 5, 2022 ODS 5, Crescimento]
Index: []