<a href="https://colab.research.google.com/github/feandresilva/exercicios_Pandas/blob/main/ODS_dataframe.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
import pandas as pd
df_ODS = pd.read_csv("https://github.com/marcelovc785/AP2_PML_8001/raw/main/IDSC_BR_AP2_E01d2G01.csv", encoding="iso-8859-1", sep= ";", decimal = ",")
df_ODS.head()

,id,Territorialidade,População_Ref,Pontuação Indice ODS 2022,Classificação 2022,2022 ODS 1,2022 ODS 3,2022 ODS 5,Pontuação Indice ODS 2019,Classificação 2019,2019 ODS 1,2019 ODS 3,2019 ODS 5
0,5200050.0,;Abadia de Goiás;GO;CO;,19128.0,48.06,2226.0,42.39,64.57,33.67,48.63,2109.0,44.36,39.52,33.67
1,3100104.0,;Abadia dos Dourados;MG;SE;,6272.0,45.65,3143.0,51.21,65.08,16.16,46.84,2688.0,53.63,69.53,16.16
2,5200100.0,;Abadiânia;GO;CO;,17228.0,49.36,1773.0,44.83,76.23,27.80,50.11,1648.0,43.71,60.24,27.80
3,3100203.0,;Abaeté;MG;SE;,22675.0,52.73,899.0,47.13,77.96,15.08,49.59,1801.0,47.60,57.21,15.08
4,1500107.0,;Abaetetuba;PA;N;,158188.0,37.92,5293.0,38.08,71.62,20.20,38.11,5215.0,37.64,56.52,20.20

Qual o estado da região Sudeste que teve o menor valor na média da “ODS 3 do

*   Item da lista
*   Item da lista


Ano 2022”, organizada por “UF”?


Qual a cidade do estado que reponde corretamente o item anterior, e que teve o valor da “ODS ano 2022” mais próximo da média do estado inteiro?


Qual foi a cidade do estado do Rio de Janeiro que teve o menor crescimento da “ODS 5” entre os anos 2019 e 2022


Aproximadamente, qual a média da "ODS 5" entre os anos 2019 e 2022 da região
Nordeste?


Qual foi o estado da região Nordeste que teve a maior média da coluna ODS 5 do ano 2022, organizada por “UF”?


Qual foi a cidade do estado que responde corretamente o item anterior que teve o maior crescimento da Coluna ODS 5 entre os anos 2019 e 2022?

Aproximadamente, qual foi a média da Pontuação Índice ODS entre os anos 2019 e 2022 da região Sudeste?

Qual a porcentagem de cidades da região Nordeste que estão acima da média da
Pontuação Índice ODS da região Sudeste?

Qual o estado da região Norte que teve o maior valor na média do ODS 3 do ano 2019?

Qual cidade do estado que reponde corretamente o item anterior, que teve
o valor da ODS 3 do ano 2019 mais próximo da média do estado?

Qual cidade do estado do Pará que teve a melhor evolução na "Classificação ODS"
entre os anos 2019 e 2022? (considere que a classificação ODS é um ranking)


Qual a porcentagem de cidades da região Norte que tem o valor da média da
ODS 1 entre os anos 2019 e 2022 acima da média desse mesmo parâmetro da região Sudeste?

In [17]:
#Qual o estado da região Sudeste que teve o menor valor na média da “ODS 3 do Ano 2022”, organizada por “UF”?
df_sem_nulos = df_ODS.dropna(subset=["Territorialidade"])
df_sem_nulos["UF"] = df_sem_nulos["Territorialidade"].str.split(";").str[2]
df_sem_nulos["Regiao"] = df_sem_nulos["Territorialidade"].str.split(";").str[3]
df_sudeste = df_sem_nulos[df_sem_nulos["Regiao"] == "SE"]
media_estados_sudeste = df_sudeste.groupby("UF")["2022 ODS 3"].mean().sort_values()
media_estados_sudeste

/tmp/ipykernel_1084/3100454592.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_sem_nulos["UF"] = df_sem_nulos["Territorialidade"].str.split(";").str[2]
/tmp/ipykernel_1084/3100454592.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_sem_nulos["Regiao"] = df_sem_nulos["Territorialidade"].str.split(";").str[3]

UF
ES    68.133846
RJ    69.518152
MG    72.152110
SP    72.278031
Name: 2022 ODS 3, dtype: float64

In [18]:
#Qual a cidade do estado que reponde corretamente o item anterior,
#e que teve o valor da “ODS ano 2022” mais próximo da média do estado inteiro?
df_sudeste_ES = df_sudeste[df_sudeste["UF"] == "ES"]
df_sudeste_ES["Diferenca"] = (68.133846 - df_sudeste_ES["2022 ODS 3"]).abs()
df_cidade_ES = df_sudeste_ES.sort_values(by="Diferenca").head(1)
df_cidade_ES

/tmp/ipykernel_1084/2627618907.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_sudeste_ES["Diferenca"] = (68.133846 - df_sudeste_ES["2022 ODS 3"]).abs()

,id,Territorialidade,População_Ref,Pontuação Indice ODS 2022,Classificação 2022,2022 ODS 1,2022 ODS 3,2022 ODS 5,Pontuação Indice ODS 2019,Classificação 2019,2019 ODS 1,2019 ODS 3,2019 ODS 5,UF,Regiao,Diferenca
5012,3205002.0,;Serra;ES;SE;,520649.0,48.19,2184.0,50.28,68.31,30.08,50.32,1603.0,49.4,56.05,30.08,ES,SE,0.176154

In [19]:
#Qual foi a cidade do estado do Rio de Janeiro que teve o menor crescimento da “ODS 3” entre os anos 2019 e 2022
df_rio = df_sudeste[df_sudeste["UF"] == "RJ"]
df_rio["Crescimento"] = df_rio["2022 ODS 3"] - df_rio["2019 ODS 3"]
df_rio.sort_values(by= "Crescimento")

/tmp/ipykernel_1084/707210297.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_rio["Crescimento"] = df_rio["2022 ODS 3"] - df_rio["2019 ODS 3"]

,id,Territorialidade,População_Ref,Pontuação Indice ODS 2022,Classificação 2022,2022 ODS 1,2022 ODS 3,2022 ODS 5,Pontuação Indice ODS 2019,Classificação 2019,2019 ODS 1,2019 ODS 3,2019 ODS 5,UF,Regiao,Crescimento
3042,3302809.0,;Mendes;RJ;SE;,17502.0,50.57,1441.0,48.84,66.68,27.69,50.22,1622.0,44.86,71.13,27.69,RJ,SE,-4.45
365,3300225.0,;Areal;RJ;SE;,11828.0,45.64,3145.0,48.12,61.96,27.30,51.21,1367.0,45.38,63.01,27.30,RJ,SE,-1.05
2845,3302452.0,;Macuco;RJ;SE;,5415.0,45.44,3226.0,46.71,59.41,20.28,45.31,3197.0,44.69,58.72,20.28,RJ,SE,0.69
5422,3306107.0,;Valença;RJ;SE;,67753.0,51.07,1279.0,42.16,51.61,28.17,48.04,2307.0,41.34,50.34,28.17,RJ,SE,1.27
3832,3304003.0,;Piraí;RJ;SE;,27474.0,50.87,1338.0,52.29,65.35,33.68,52.83,1057.0,51.45,61.02,33.68,RJ,SE,4.33
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1134,3301207.0,;Carmo;RJ;SE;,17198.0,52.82,880.0,51.18,72.54,20.52,49.68,1777.0,49.37,48.80,20.52,RJ,SE,23.74
5293,3306008.0,;Três Rios;RJ;SE;,78346.0,50.83,1361.0,43.34,72.85,53.10,52.80,1062.0,47.92,47.34,53.10,RJ,SE,25.51
3604,3303807.0,;Paraty;RJ;SE;,44872.0,47.57,2403.0,32.73,74.53,53.83,46.90,2662.0,31.33,48.85,53.83,RJ,SE,25.68
3572,3303708.0,;Paraíba do Sul;RJ;SE;,42063.0,46.63,2758.0,43.05,76.88,21.05,45.86,3031.0,44.59,51.11,21.05,RJ,SE,25.77
2354,3302106.0,;Itaocara;RJ;SE;,22919.0,47.65,2377.0,46.54,72.23,20.40,49.23,1922.0,51.88,40.66,20.40,RJ,SE,31.57

In [20]:
#Aproximadamente, qual a média da "ODS 5" entre os anos 2019 e 2022 da região Nordeste?
df_nordeste = df_sem_nulos[df_sem_nulos["Regiao"] == "NE"]
df_nordeste["Media ODS 5 2019"] = df_nordeste["2019 ODS 5"].mean()
df_nordeste["Media ODS 5 2022"] = df_nordeste["2022 ODS 5"].mean()
df_nordeste_media_final = (df_nordeste["Media ODS 5 2022"] + df_nordeste["Media ODS 5 2019"]) / 2
df_nordeste_media_final.head(1)

/tmp/ipykernel_1084/3095460803.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_nordeste["Media ODS 5 2019"] = df_nordeste["2019 ODS 5"].mean()
/tmp/ipykernel_1084/3095460803.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_nordeste["Media ODS 5 2022"] = df_nordeste["2022 ODS 5"].mean()

5    18.202651
dtype: float64

In [21]:
#Qual foi o estado da região Nordeste que teve a maior média da coluna ODS 3 do ano 2022, organizada por “UF”?
media_estados_nordeste = df_nordeste.groupby("UF")["2022 ODS 3"].mean().sort_values(ascending=False)
media_estados_nordeste

UF
RN    76.449341
PB    75.409283
PI    74.791429
AL    73.679804
MA    72.921705
SE    72.656267
BA    72.107194
PE    71.884865
CE    71.678098
Name: 2022 ODS 3, dtype: float64

In [28]:
#Qual foi a cidade do estado que responde corretamente o item anterior
#que teve o maior crescimento da Coluna ODS 3 entre os anos 2019 e 2022?
df_RN = df_nordeste[df_nordeste["UF"]== "RN"]
df_RN["Crescimento"] = df_RN["2022 ODS 3"] - df_RN["2019 ODS 3"]
df_RN.sort_values(by="Crescimento", ascending=False)

/tmp/ipykernel_1084/956748757.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_RN["Crescimento"] = df_RN["2022 ODS 3"] - df_RN["2019 ODS 3"]

,id,Territorialidade,População_Ref,Pontuação Indice ODS 2022,Classificação 2022,2022 ODS 1,2022 ODS 3,2022 ODS 5,Pontuação Indice ODS 2019,Classificação 2019,2019 ODS 1,2019 ODS 3,2019 ODS 5,UF,Regiao,Media ODS 5 2019,Media ODS 5 2022,Media_Pontuacao_Indice_ODS,Crescimento
2804,2406908.0,;Lucrécia;RN;NE;,3490.0,50.84,1356.0,58.14,77.71,33.47,55.69,565.0,53.26,45.24,33.47,RN,NE,18.202815,18.202486,53.265,32.47
2610,2406007.0,;José da Penha;RN;NE;,5803.0,44.63,3530.0,36.53,78.23,13.75,41.31,4463.0,31.46,46.45,13.75,RN,NE,18.202815,18.202486,42.970,31.78
2981,2407401.0,;Martins;RN;NE;,8179.0,44.44,3582.0,47.06,77.20,13.74,42.15,4176.0,41.54,46.91,13.74,RN,NE,18.202815,18.202486,43.295,30.29
5229,2414209.0,;Tibau do Sul;RN;NE;,16929.0,45.44,3227.0,31.58,78.64,34.00,46.74,2727.0,32.25,50.73,34.00,RN,NE,18.202815,18.202486,46.090,27.91
4912,2412906.0,;São Tomé;RN;NE;,9972.0,43.85,3785.0,34.19,81.45,8.41,42.90,3955.0,27.32,53.82,8.41,RN,NE,18.202815,18.202486,43.375,27.63
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5115,2413805.0,;Taboleiro Grande;RN;NE;,2338.0,38.55,5214.0,44.47,69.86,14.39,44.64,3418.0,40.11,65.57,14.39,RN,NE,18.202815,18.202486,41.595,4.29
4096,2410603.0,;Rafael Godeiro;RN;NE;,2934.0,41.68,4516.0,47.46,58.55,0.68,40.54,4679.0,42.42,54.50,0.68,RN,NE,18.202815,18.202486,41.110,4.05
1028,2402204.0,;Canguaretama;RN;NE;,29668.0,42.94,4092.0,34.32,73.62,34.34,42.30,4129.0,30.75,72.01,34.34,RN,NE,18.202815,18.202486,42.620,1.61
4854,2412609.0,;São Paulo do Potengi;RN;NE;,16786.0,46.63,2759.0,38.76,64.04,6.94,45.66,3084.0,28.97,62.99,6.94,RN,NE,18.202815,18.202486,46.145,1.05
3312,2408300.0,;Nova Cruz;RN;NE;,34269.0,50.04,1586.0,26.40,67.99,13.50,49.22,1924.0,21.66,69.79,13.50,RN,NE,18.202815,18.202486,49.630,-1.80

In [23]:
#Aproximadamente, qual foi a média da Pontuação Índice ODS entre os anos 2019 e 2022 da região Sudeste?
df_sudeste["Media Pontuacao Indice 2019"] = df_sudeste["Pontuação Indice ODS 2019"].mean()
df_sudeste["Media Pontuacao Indice 2022"] = df_sudeste["Pontuação Indice ODS 2022"].mean()
df_sudeste_media_indice = (df_sudeste["Media Pontuacao Indice 2019"] + df_sudeste["Media Pontuacao Indice 2022"]) / 2
df_sudeste_media_indice.head(1)

/tmp/ipykernel_1084/2380549981.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_sudeste["Media Pontuacao Indice 2019"] = df_sudeste["Pontuação Indice ODS 2019"].mean()
/tmp/ipykernel_1084/2380549981.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_sudeste["Media Pontuacao Indice 2022"] = df_sudeste["Pontuação Indice ODS 2022"].mean()

1    51.788264
dtype: float64

In [24]:
#Qual a porcentagem de cidades da região Nordeste que estão acima da média da Pontuação Índice ODS da região Sudeste (valor da questão anterior)?
df_nordeste["Media_Pontuacao_Indice_ODS"] = (df_nordeste["Pontuação Indice ODS 2022"] + df_nordeste["Pontuação Indice ODS 2019"]) / 2
df_nordeste_filtrado = df_nordeste[df_nordeste["Media_Pontuacao_Indice_ODS"] > 51.788264]
(df_nordeste_filtrado.size / df_nordeste.size) *100

/tmp/ipykernel_1084/3814849345.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_nordeste["Media_Pontuacao_Indice_ODS"] = (df_nordeste["Pontuação Indice ODS 2022"] + df_nordeste["Pontuação Indice ODS 2019"]) / 2

0.6131549609810479

In [25]:
#Qual o estado da região Norte que teve o maior valor na média do ODS 3 do ano 2019?
df_norte = df_sem_nulos[df_sem_nulos["Regiao"]== "N"]
df_norte_media_ODS_3 = df_norte.groupby("UF")["2019 ODS 3"].mean().sort_values(ascending=False)
df_norte_media_ODS_3

UF
RO    57.703269
TO    57.181655
PA    56.749931
RR    55.921333
AC    54.518182
AP    53.205000
AM    52.942419
Name: 2019 ODS 3, dtype: float64

In [26]:
#Qual cidade do estado que reponde corretamente o item anterior, que teve o valor da ODS 3 do ano 2019 mais próximo da média do estado?
df_RO = df_norte[df_norte["UF"]== "RO"]
df_RO["Diferenca"] = (57.703269 - df_norte["2019 ODS 3"]).abs()
df_RO.sort_values(by="Diferenca").head(1)

/tmp/ipykernel_1084/3316464542.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_RO["Diferenca"] = (57.703269 - df_norte["2019 ODS 3"]).abs()

,id,Territorialidade,População_Ref,Pontuação Indice ODS 2022,Classificação 2022,2022 ODS 1,2022 ODS 3,2022 ODS 5,Pontuação Indice ODS 2019,Classificação 2019,2019 ODS 1,2019 ODS 3,2019 ODS 5,UF,Regiao,Diferenca
4841,1100320.0,;São Miguel do Guaporé;RO;N;,21635.0,42.34,4290.0,47.62,66.69,32.8,38.95,5057.0,40.83,57.71,32.8,RO,N,0.006731

In [29]:
#Qual cidade do estado do Pará que teve a melhor evolução na "Classificação ODS" entre os anos 2019 e 2022?
#(considere que a classificação ODS é um ranking)
df_Para = df_norte[df_norte["UF"]== "PA"]
df_Para["Evolucao"] = df_Para["Classificação 2022"] - df_Para["Classificação 2019"]
df_Para.sort_values(by="Evolucao")

/tmp/ipykernel_1084/2066235485.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_Para["Evolucao"] = df_Para["Classificação 2022"] - df_Para["Classificação 2019"]

,id,Territorialidade,População_Ref,Pontuação Indice ODS 2022,Classificação 2022,2022 ODS 1,2022 ODS 3,2022 ODS 5,Pontuação Indice ODS 2019,Classificação 2019,2019 ODS 1,2019 ODS 3,2019 ODS 5,UF,Regiao,Evolucao
1741,1503002.0,;Faro;PA;N;,8728.0,48.52,2073.0,26.18,70.69,80.73,38.45,5156.0,24.44,61.65,80.73,PA,N,-3083.0
596,1501451.0,;Belterra;PA;N;,18099.0,43.06,4052.0,33.42,77.80,51.02,37.33,5311.0,34.25,57.12,51.02,PA,N,-1259.0
500,1501303.0,;Barcarena;PA;N;,126650.0,45.65,3142.0,29.17,73.84,26.87,41.77,4308.0,25.19,58.28,26.87,PA,N,-1166.0
843,1502004.0,;Cachoeira do Arari;PA;N;,23981.0,43.98,3744.0,23.72,72.76,52.60,40.37,4718.0,17.83,59.90,52.60,PA,N,-974.0
456,1501204.0,;Baião;PA;N;,51641.0,43.02,4070.0,24.44,73.28,40.02,39.32,4980.0,23.67,61.40,40.02,PA,N,-910.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10,1500131.0,;Abel Figueiredo;PA;N;,7030.0,36.29,5442.0,27.25,72.76,28.50,40.27,4747.0,29.09,62.71,28.50,PA,N,695.0
4523,1506906.0,;Santarém Novo;PA;N;,6116.0,36.27,5444.0,32.92,81.07,4.41,40.46,4700.0,37.51,57.52,4.41,PA,N,744.0
584,1501402.0,;Belém;PA;N;,1303389.0,39.98,4949.0,39.48,55.06,28.63,42.58,4050.0,39.81,42.57,28.63,PA,N,899.0
5090,1507904.0,;Soure;PA;N;,24204.0,37.77,5314.0,27.00,80.68,55.94,41.51,4397.0,25.81,60.69,55.94,PA,N,917.0
4374,1506401.0,;Santa Cruz do Arari;PA;N;,7445.0,37.00,5382.0,22.73,74.64,42.34,41.39,4446.0,21.44,64.60,42.34,PA,N,936.0

In [42]:
#Qual a porcentagem de cidades da região Norte que tem o valor da média da ODS 1
#entre os anos 2019 e 2022 acima da média desse mesmo parâmetro da região Sudeste?
df_sudeste["Media ODS 1 2019"] = df_sudeste["2019 ODS 1"].mean()
df_sudeste["Media ODS 1 2022"] = df_sudeste["2022 ODS 1"].mean()
df_sudeste_media_final_ODS1 = (df_sudeste["Media ODS 1 2019"] + df_sudeste["Media ODS 1 2022"])/2 #A médiado Sudeste é de 52.507254

df_norte["Media_ODS_1_2019_2022"] = (df_norte["2022 ODS 1"] + df_norte["2019 ODS 1"])/2
df_norte_filtrado = df_norte[df_norte["Media_ODS_1_2019_2022"]> 52.507254]
df_norte_filtrado
(df_norte_filtrado.size / df_norte.size)*100

/tmp/ipykernel_1084/498059939.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_sudeste["Media ODS 1 2019"] = df_sudeste["2019 ODS 1"].mean()
/tmp/ipykernel_1084/498059939.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_sudeste["Media ODS 1 2022"] = df_sudeste["2022 ODS 1"].mean()
/tmp/ipykernel_1084/498059939.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_norte["Media_ODS_1_2019_2022"] = (df_norte["2022 ODS 1"] + df_norte["2019 ODS 1"])/2

2.2222222222222223